services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ulms_local
      POSTGRES_PASSWORD: mysecurepassword
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    # volumes:
    #   - minio-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

# volumes:
#   postgres_data:
#   minio-data: