server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ulms_local
    username: postgres
    password: mysecurepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
#    change-log: classpath:/db/changelog/changelog-master.yaml
    clear-checksums: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: umls
            #            client-secret: myclientsecret
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dev
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/dev/protocol/openid-connect/certs

# ✅ إضافة إعدادات Keycloak Admin Client
keycloak:
  auth-server-url: http://localhost:8080
  realm: dev  # تأكد أنه نفس الاسم في Keycloak
  client-id: umls-admin
  client-secret: pqlup7oMaQH1OYpeFWUKXbHcDWS0zbPe
  scope: open-id
  grant-type: client_credentials

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket: ulms-files

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html