spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ulms_local
    username: postgres
    password: mysecurepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
#    clear-checksums: true