package seu.ulms.entities.book;

//public enum EFileType {
//    PDF,WORD,EXCEL,EXCEL_DOC,DOCX,EXCEL_XLS,IMAGE_PNG, IMAGE_JPEG, IMAGE_JPG,
//}

public enum EFileType {
    APPLICATION_PDF,
    APPLICATION_MSWORD,
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT, // docx
    APPLICATION_VND_MS_EXCEL,
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET, // xlsx
    IMAGE_PNG,
    IMAGE_JPEG,
    IMAGE_JPG
}